### ISSUE TITLE
Endianess of the BcBlock structs

### ISSUE THREAD

**Issue by onepiecefreak3** [Nominom/BCnEncoder.NET#20]
I'm currently working on implementing ATC and I noticed how the Blocks are actually cast and read now. The current approach of casting the memory containing the blocks to the struct type only works out if the executing architecture is Little Endian.
The current code only works since all Block Compressions are specified as being stored in Little Endian, so a LE architecture has no trouble with the code.

Is it a concern that the library should work independant from the architecture of the executing system?

**Comment by Nominom** [comment]
Hmm. The [ktx file format specification](http://github.khronos.org/KTX-Specification/) says that all data including the headers is always in little-endian. I would assume dds is the same. `BinaryReader` and `BinaryWriter` work little-endian always, so the files should be read correctly. `MemoryMarshal.Cast` seems to read endianness based on the architecture (like you pointed out) , so that might mess up things. 

Do you have an easy-fix proposal or something similar? Essentially, big-endian is already dead. Anything new enough to be able to run Net core 3 is most likely a little-endian system. So if it takes more than writing like 10 lines of code to fix, I feel like it's not worth it.

**Comment by onepiecefreak3** [comment]
I think there is no solution that could fix it this quickly or easily. Then I close this issue since I otherwise agree with you.
